services:
  web:
    image: fueltracker:local
    container_name: fuel-tracker-web
    command: python app.py
    volumes:
      - ./data:/app/data
    ports:
      - 5000:5000
    restart: unless-stopped
  scheduler:
    image: fueltracker:local
    container_name: fuel-tracker-scheduler
    command: python scheduler.py
    volumes:
      - ./data:/app/data
    restart: unless-stopped
networks: {}
